author: vemacs
main: me.vemacs.executeeverywhere.bukkit.ExecuteEverywhere
name: ExecuteEverywhere
version: ${version}
commands:
  ee:
    description: Dispatches a command for execution to all connected Bukkit servers.
    aliases: [executeeverywhere]
    permission: executeeverywhere.use
    usage: /ee <cmd>
    permission-message: You don't have permission to use this.
  eb:
    description: Dispatches a command for execution to all connected BungeeCord servers.
    aliases: [executebungee]
    permission: executeeverywhere.use
    usage: /eb <cmd>
    permission-message: You don't have permission to use this.
  eeg:
    description: Dispatches a command for execution to all connected servers in a group.
    aliases: [executegroup]
    permission: executeeverywhere.use
    usage: /eeg <group> <cmd>
    permission-message: You don't have permission to use this.
permissions:
  executeeverywhere.use:
    description: Lets you dispatch a command for execution on all servers.
    default: op
